### ISSUE TITLE
Why is it obfuscated 

### ISSUE THREAD

**Issue by ThonkPT** [DiscordRatStopper/AnarchyGrabber-Remover#1]
why is this shit obfuscated lmaoooooooooo shady af

**Comment by DiscordRatStopper** [comment]
This is obfuscated so the devs of AG3 cannot patch the remover.

**Comment by ThonkPT** [comment]
brruhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by ThonkPT** [comment]
github is for sharing open source apps not heavily obfuscated exes

**Comment by ThonkPT** [comment]
love how virus total flags it just like it flags the actual anarchy grabber
